import Head from 'next/head'
import Contents from '../components/Contents'
import Footer from '../components/Footer'
import Headline from '../components/Headline'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Headline page="About">
          <code className={styles.code}>pages/about.js</code>
        </Headline>
        <Contents />
      </main>

      <Footer />
    </div>
  )
}
